### ISSUE TITLE
Intermittent test failures especially in test_search

### ISSUE THREAD

**Issue by jayvdb** [loklak/loklak_python_api#58]
Investigating the build failures on #57.

The #57  build status were:
1. [green](https://travis-ci.org/loklak/loklak_python_api/builds/159642244)
2. [green](https://travis-ci.org/loklak/loklak_python_api/builds/159647275)
3. [red](https://travis-ci.org/loklak/loklak_python_api/builds/159654155) - [py2.7](https://travis-ci.org/loklak/loklak_python_api/jobs/159654156) - `test_search`
4. [red](https://travis-ci.org/loklak/loklak_python_api/builds/159657566) - [py3.5](https://travis-ci.org/loklak/loklak_python_api/jobs/159657573) - `test_search`
5. [red](https://travis-ci.org/loklak/loklak_python_api/builds/159662250) - py3.5 - `test_search` and `test_peers`

I have done some Travis builds of master (78456e7), with results:
1. [green](https://travis-ci.org/jayvdb/loklak_python_api/builds/159736663)
2. [red](https://travis-ci.org/jayvdb/loklak_python_api/builds/159739245) - [py35](https://travis-ci.org/jayvdb/loklak_python_api/jobs/159739247) - `test_search`
3. [green](https://travis-ci.org/jayvdb/loklak_python_api/builds/159739990)
4. [red](https://travis-ci.org/jayvdb/loklak_python_api/builds/159741503) - [py27](https://travis-ci.org/jayvdb/loklak_python_api/jobs/159741504) - `test_search`

The test_peers failure has only occurred once so far.

```python
$ nosetests --with-coverage tests
....F.F...
======================================================================
FAIL: Test finding peers.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/loklak/loklak_python_api/tests/test.py", line 77, in test_peers
    self.assertTrue('peers' in result)
AssertionError: False is not true
...
```

The logging is always correctly reporting:
```
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): loklak.org
requests.packages.urllib3.connectionpool: DEBUG: "GET /api/search.json?count=18&query=doctor+who HTTP/1.1" 200 None
```

The `test_search` failures on Python 3.5 is always in the number of results:

```python
$ nosetests --with-coverage tests
......F...
======================================================================
FAIL: test search result
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/jayvdb/loklak_python_api/tests/test.py", line 108, in test_search
    self.assertEqual(int(result['search_metadata']['count']), 18)
AssertionError: 17 != 18
```

https://travis-ci.org/loklak/loklak_python_api/jobs/159657573 is slightly different, with fewer returned results
```python
$ nosetests --with-coverage tests
......F...
======================================================================
FAIL: Test search result.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/loklak/loklak_python_api/tests/test.py", line 110, in test_search
    self.assertEqual(int(result['search_metadata']['count']), 18)
AssertionError: 13 != 18
```

And this one only has 10 results:
https://travis-ci.org/loklak/loklak_python_api/jobs/159662252
```python
======================================================================
FAIL: Test search result.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/loklak/loklak_python_api/tests/test.py", line 110, in test_search
    self.assertEqual(int(result['search_metadata']['count']), 18)
AssertionError: 10 != 18
```

On Python 2.7 it varies more, with higher results and other problems.

https://travis-ci.org/jayvdb/loklak_python_api/jobs/159741504 :
```python
$ nosetests --with-coverage tests
......F...
======================================================================
FAIL: test search result
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/jayvdb/loklak_python_api/tests/test.py", line 105, in test_search
    self.assertTrue(len(result['statuses']) >= 1)
AssertionError: False is not true
```

https://travis-ci.org/loklak/loklak_python_api/jobs/159654156 :
```python
$ nosetests --with-coverage tests
......F...
======================================================================
FAIL: Test search result.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/loklak/loklak_python_api/tests/test.py", line 109, in test_search
    int(result['search_metadata']['count']))
AssertionError: 24 != 14
```

**Comment by jayvdb** [comment]
On my second rebuild of #55 (2507e28) , [it failed with](https://travis-ci.org/jayvdb/loklak_python_api/builds/159750472)

```python
$ nosetests --with-coverage tests
......F...
======================================================================
FAIL: test search result
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/jayvdb/loklak_python_api/tests/test.py", line 108, in test_search
    self.assertEqual(int(result['search_metadata']['count']), 18)
AssertionError: 14 != 18
```

After another 10 rebuilds, it [failed again](https://travis-ci.org/jayvdb/loklak_python_api/builds/159759496):

```python
$ nosetests --with-coverage tests
......F...
======================================================================
FAIL: test search result
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/jayvdb/loklak_python_api/tests/test.py", line 108, in test_search
    self.assertEqual(int(result['search_metadata']['count']), 18)
AssertionError: 10 != 18
```

Seems like something is wrong server side.

**Comment by jayvdb** [comment]
A simple way to reduce the number of failures ( & pretend it doesnt exist) is to assert the results are less than 18 hits.

**Comment by sudheesh001** [comment]
A simpler way to do this is by having the API responses be `mocked` rather than making an actual request. Would you want to pick this issue @jayvdb

**Comment by jayvdb** [comment]
Sorry, I would much rather be spending my time analyzing the bug and fixing it.

**Comment by jayvdb** [comment]
Continuing from #57 :

> It looks like travis is failing because loklak's production api's on loklak.org return a 503.

@sudheesh001 , How did you arrive at the conclusion that it is returning a 503?

That conclusion seems inconsistent with the API returning 24 results instead of 18 at https://travis-ci.org/loklak/loklak_python_api/jobs/159654156 .

**Comment by sudheesh001** [comment]
I think this was with in the previous push when the server might be acting up. https://travis-ci.org/loklak/loklak_python_api/jobs/159662252

```log
======================================================================
FAIL: Test finding peers.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/loklak/loklak_python_api/tests/test.py", line 77, in test_peers
    self.assertTrue('peers' in result)
AssertionError: False is not true
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): loklak.org
requests.packages.urllib3.connectionpool: DEBUG: "GET /api/peers.json HTTP/1.1" 503 381
--------------------- >> end captured logging << ---------------------
```
And yes you're right it looks like it's returning 24, that seems like a server side problem since the server decides the result, the API only bring it to the developers, please open an issue on loklak/loklak_server for the same.

https://github.com/loklak/loklak_server
